
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\t\xa4\x11)\x88\xe1H\xde\x81\xa9\x94\xaf8.D-'
    
_lr_action_items = {'STRING':([24,25,26,27,49,],[43,44,45,46,51,]),'CURRENT_MONTH':([15,],[31,]),'COMMA':([46,47,48,51,],[-22,49,50,-23,]),'GT':([2,9,13,],[16,-18,-2,]),'PART_DESCRIPTION':([0,7,19,20,],[4,4,4,4,]),'BEFORE':([2,9,13,],[17,-18,-2,]),'LEFT_PAREN':([0,7,15,19,20,],[7,7,30,7,7,]),'SLIP_ACTIVE':([0,7,19,20,],[8,8,8,8,]),'RIGHT_PAREN':([1,5,6,9,12,13,21,28,29,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,51,52,53,],[-1,-25,-26,-18,-24,-2,38,-13,-17,-21,-20,-14,-15,-16,-11,-10,-12,-8,-6,-9,-7,-4,-27,-28,-22,-29,-23,53,-19,]),'AFTER':([2,9,13,],[14,-18,-2,]),'FALSE':([22,23,],[39,41,]),'DATE':([0,7,14,16,17,18,19,20,30,50,],[9,9,9,9,9,9,9,9,48,52,]),'$end':([1,3,5,6,9,12,13,28,29,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,51,53,],[-1,0,-25,-26,-18,-24,-2,-13,-17,-21,-20,-14,-15,-16,-11,-10,-12,-8,-6,-9,-7,-4,-27,-28,-22,-29,-23,-19,]),'EQUALS':([4,8,10,11,],[-3,23,24,25,]),'IN':([2,4,9,10,11,13,],[15,-3,-18,-5,27,-2,]),'CUSTOMER_NAME':([0,7,19,20,],[10,10,10,10,]),'TRUE':([22,23,],[40,42,]),'LT':([2,9,13,],[18,-18,-2,]),'MONTH_BEFORE':([15,],[32,]),'IS':([8,],[22,]),'TILDE':([4,10,11,],[-3,-5,26,]),'CREATION_DATE':([0,7,14,16,17,18,19,20,],[13,13,13,13,13,13,13,13,]),'OR':([1,3,5,6,9,12,13,21,28,29,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,51,53,],[-1,19,-25,-26,-18,-24,-2,19,-13,-17,-21,-20,-14,-15,-16,-11,-10,-12,-8,-6,-9,-7,-4,-27,-28,-22,-29,-23,-19,]),'AND':([1,3,5,6,9,12,13,21,28,29,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,51,53,],[-1,20,-25,-26,-18,-24,-2,20,-13,-17,-21,-20,-14,-15,-16,-11,-10,-12,-8,-6,-9,-7,-4,-27,-28,-22,-29,-23,-19,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'date_after_expression':([0,7,19,20,],[12,12,12,12,]),'date_before_expression':([0,7,19,20,],[5,5,5,5,]),'term':([0,7,19,20,],[1,1,36,37,]),'list':([27,],[47,]),'date_term':([0,7,14,16,17,18,19,20,],[2,2,28,33,34,35,2,2,]),'date_in_period_expression':([0,7,19,20,],[6,6,6,6,]),'text_term':([0,7,19,20,],[11,11,11,11,]),'bool_expression':([0,7,],[3,21,]),'period_term':([15,],[29,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> bool_expression","S'",1,None,None,None),
  ('bool_expression -> term','bool_expression',1,'p_expression_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\delivery_slip_query_parser.py',101),
  ('date_term -> CREATION_DATE','date_term',1,'p_creation_date_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\delivery_slip_query_parser.py',106),
  ('text_term -> PART_DESCRIPTION','text_term',1,'p_part_description','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\delivery_slip_query_parser.py',110),
  ('term -> CUSTOMER_NAME EQUALS STRING','term',3,'p_customer_name_equals','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\delivery_slip_query_parser.py',114),
  ('text_term -> CUSTOMER_NAME','text_term',1,'p_customer_name','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\delivery_slip_query_parser.py',124),
  ('term -> SLIP_ACTIVE IS TRUE','term',3,'p_order_is_active','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\delivery_slip_query_parser.py',129),
  ('term -> SLIP_ACTIVE EQUALS TRUE','term',3,'p_order_is_active','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\delivery_slip_query_parser.py',130),
  ('term -> SLIP_ACTIVE IS FALSE','term',3,'p_order_is_not_active','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\delivery_slip_query_parser.py',134),
  ('term -> SLIP_ACTIVE EQUALS FALSE','term',3,'p_order_is_not_active','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\delivery_slip_query_parser.py',135),
  ('bool_expression -> bool_expression AND term','bool_expression',3,'p_and_expression','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\parser_utils.py',155),
  ('bool_expression -> bool_expression OR term','bool_expression',3,'p_or_expression','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\parser_utils.py',160),
  ('term -> LEFT_PAREN bool_expression RIGHT_PAREN','term',3,'p_term_parenthesis','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\parser_utils.py',166),
  ('date_after_expression -> date_term AFTER date_term','date_after_expression',3,'p_date_after_expression','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\parser_utils.py',172),
  ('date_after_expression -> date_term GT date_term','date_after_expression',3,'p_date_after_expression','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\parser_utils.py',173),
  ('date_before_expression -> date_term BEFORE date_term','date_before_expression',3,'p_date_before_expression','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\parser_utils.py',178),
  ('date_before_expression -> date_term LT date_term','date_before_expression',3,'p_date_before_expression','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\parser_utils.py',179),
  ('date_in_period_expression -> date_term IN period_term','date_in_period_expression',3,'p_date_in_period_expression','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\parser_utils.py',184),
  ('date_term -> DATE','date_term',1,'p_date_term_encoded','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\parser_utils.py',191),
  ('period_term -> LEFT_PAREN DATE COMMA DATE RIGHT_PAREN','period_term',5,'p_period_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\parser_utils.py',197),
  ('period_term -> MONTH_BEFORE','period_term',1,'p_period_function_month_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\parser_utils.py',202),
  ('period_term -> CURRENT_MONTH','period_term',1,'p_period_function_current_month_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\parser_utils.py',210),
  ('list -> STRING','list',1,'p_string_list','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\parser_utils.py',220),
  ('list -> list COMMA STRING','list',3,'p_string_list_l','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\parser_utils.py',226),
  ('term -> date_after_expression','term',1,'p_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\parser_utils.py',232),
  ('term -> date_before_expression','term',1,'p_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\parser_utils.py',233),
  ('term -> date_in_period_expression','term',1,'p_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\parser_utils.py',234),
  ('term -> text_term EQUALS STRING','term',3,'p_string_eql_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\parser_utils.py',238),
  ('term -> text_term TILDE STRING','term',3,'p_string_tilde_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\parser_utils.py',242),
  ('term -> text_term IN list','term',3,'p_in_list_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\parser_utils.py',246),
]
