
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'Vf\x807\x86\x14\x81"PX\xae3\x0c=\x11\xdf'
    
_lr_action_items = {'OR':([3,5,7,8,11,12,13,14,21,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,46,47,48,51,54,],[-17,20,-22,-10,-23,-18,-1,-16,20,-14,-21,-20,-19,-25,-2,-3,-4,-29,-27,-30,-28,-8,-6,-13,-9,-12,-7,-5,-15,-11,]),'STRING':([15,16,17,18,49,],[29,31,32,33,51,]),'GT':([7,8,10,11,],[-22,-10,25,-23,]),'IS':([9,],[22,]),'TILDE':([1,2,4,],[16,-24,-26,]),'MONTH_BEFORE':([26,],[46,]),'AFTER':([7,8,10,11,],[-22,-10,28,-23,]),'COMMA':([29,30,50,51,],[-14,49,52,-15,]),'LEFT_PAREN':([0,6,19,20,26,],[6,6,6,6,45,]),'PART_DESCRIPTION':([0,6,19,20,],[2,2,2,2,]),'FALSE':([22,23,],[37,39,]),'AND':([3,5,7,8,11,12,13,14,21,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,46,47,48,51,54,],[-17,19,-22,-10,-23,-18,-1,-16,19,-14,-21,-20,-19,-25,-2,-3,-4,-29,-27,-30,-28,-8,-6,-13,-9,-12,-7,-5,-15,-11,]),'SUPPLIER_NAME':([0,6,19,20,],[4,4,4,4,]),'BEFORE':([7,8,10,11,],[-22,-10,27,-23,]),'CREATION_DATE':([0,6,19,20,24,25,27,28,],[7,7,7,7,7,7,7,7,]),'RIGHT_PAREN':([3,7,8,11,12,13,14,21,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,46,47,48,51,53,54,],[-17,-22,-10,-23,-18,-1,-16,36,-14,-21,-20,-19,-25,-2,-3,-4,-29,-27,-30,-28,-8,-6,-13,-9,-12,-7,-5,-15,54,-11,]),'$end':([3,5,7,8,11,12,13,14,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,46,47,48,51,54,],[-17,0,-22,-10,-23,-18,-1,-16,-14,-21,-20,-19,-25,-2,-3,-4,-29,-27,-30,-28,-8,-6,-13,-9,-12,-7,-5,-15,-11,]),'TRUE':([22,23,],[38,40,]),'ORDER_ACTIVE':([0,6,19,20,],[9,9,9,9,]),'LT':([7,8,10,11,],[-22,-10,24,-23,]),'EXPECTED_DELIVERY_DATE':([0,6,19,20,24,25,27,28,],[11,11,11,11,11,11,11,11,]),'CURRENT_MONTH':([26,],[43,]),'IN':([1,2,4,7,8,10,11,],[15,-24,-26,-22,-10,26,-23,]),'DATE':([0,6,19,20,24,25,27,28,45,52,],[8,8,8,8,8,8,8,8,50,53,]),'EQUALS':([1,2,4,9,],[17,-24,18,23,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'period_term':([26,],[44,]),'bool_expression':([0,6,],[5,21,]),'list':([15,],[30,]),'date_in_period_expression':([0,6,19,20,],[12,12,12,12,]),'term':([0,6,19,20,],[13,13,34,35,]),'text_term':([0,6,19,20,],[1,1,1,1,]),'date_before_expression':([0,6,19,20,],[3,3,3,3,]),'date_after_expression':([0,6,19,20,],[14,14,14,14,]),'date_term':([0,6,19,20,24,25,27,28,],[10,10,10,10,41,42,47,48,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> bool_expression","S'",1,None,None,None),
  ('bool_expression -> term','bool_expression',1,'p_expression_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',237),
  ('bool_expression -> bool_expression AND term','bool_expression',3,'p_and_expression','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',243),
  ('bool_expression -> bool_expression OR term','bool_expression',3,'p_or_expression','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',248),
  ('term -> LEFT_PAREN bool_expression RIGHT_PAREN','term',3,'p_term_parenthesis','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',254),
  ('date_after_expression -> date_term AFTER date_term','date_after_expression',3,'p_date_after_expression','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',260),
  ('date_after_expression -> date_term GT date_term','date_after_expression',3,'p_date_after_expression','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',261),
  ('date_before_expression -> date_term BEFORE date_term','date_before_expression',3,'p_date_before_expression','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',266),
  ('date_before_expression -> date_term LT date_term','date_before_expression',3,'p_date_before_expression','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',267),
  ('date_in_period_expression -> date_term IN period_term','date_in_period_expression',3,'p_date_in_period_expression','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',272),
  ('date_term -> DATE','date_term',1,'p_date_term_encoded','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',279),
  ('period_term -> LEFT_PAREN DATE COMMA DATE RIGHT_PAREN','period_term',5,'p_period_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',285),
  ('period_term -> MONTH_BEFORE','period_term',1,'p_period_function_month_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',290),
  ('period_term -> CURRENT_MONTH','period_term',1,'p_period_function_current_month_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',297),
  ('list -> STRING','list',1,'p_string_list','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',305),
  ('list -> list COMMA STRING','list',3,'p_string_list_l','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',311),
  ('term -> date_after_expression','term',1,'p_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',317),
  ('term -> date_before_expression','term',1,'p_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',318),
  ('term -> date_in_period_expression','term',1,'p_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',319),
  ('term -> text_term EQUALS STRING','term',3,'p_string_eql_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',323),
  ('term -> text_term TILDE STRING','term',3,'p_string_tilde_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',327),
  ('term -> text_term IN list','term',3,'p_in_list_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',331),
  ('date_term -> CREATION_DATE','date_term',1,'p_creation_date_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',351),
  ('date_term -> EXPECTED_DELIVERY_DATE','date_term',1,'p_expected_delivery_date_term','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',355),
  ('text_term -> PART_DESCRIPTION','text_term',1,'p_part_description','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',359),
  ('term -> SUPPLIER_NAME EQUALS STRING','term',3,'p_supplier_name_equals','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',363),
  ('text_term -> SUPPLIER_NAME','text_term',1,'p_supplier_name','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',370),
  ('term -> ORDER_ACTIVE IS TRUE','term',3,'p_order_is_active','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',375),
  ('term -> ORDER_ACTIVE EQUALS TRUE','term',3,'p_order_is_active','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',376),
  ('term -> ORDER_ACTIVE IS FALSE','term',3,'p_order_is_not_active','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',380),
  ('term -> ORDER_ACTIVE EQUALS FALSE','term',3,'p_order_is_not_active','C:\\PORT-STC\\PRIVATE\\PL\\horse\\koi\\datalayer\\supply_order_query_parser.py',381),
]
